language: node_js

node_js:
  - "v17"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/multi_fruit_tests

before_script:
  - psql -c 'create database  multi_fruit_tests' -U postgres
  - psql -U postgres -d multi_fruit_tests -a -f tables.sql

services:
  - postgresql  